### ISSUE TITLE
change separators

### ISSUE THREAD

**Issue by cysouw** [cysouw/msa-editor#13]
There are currently two ideas floating around how to manage linguistic multi alignments: either by separating the columns by tabs, or by spaces.

The good thing of spaces is that than the tabs can be used for real column separators in TSV-files. I think spaces are only very in frequently necessary as actual character, so in those few cases we can propose that the spaces should be replaced by something different.

So: Let's just move to SPACE as separator for multi alignments everywhere.

@FrankNagel lets do the following:

- keep the current msa-editor as it is, but rename it something like msa-editor-old (just for backward compatibility)
- a new version of the current msa-editor should then work for TSV-files with three columns only (ID, NAME, ALIGNMENT), and the alignment column should be separated by spaces

further:
- the editor assumes that there is no header line: simply all lines are taken as data
- However, we keep the assumption that all lines starting with ":ANN" in the ID-column are treated as some kind of special header. There can be multiple of such headers

finally:
- no inline comments are allowed! So no ignoring of lines starting with "#" or something like that. All metadata will be put into different files...

(note that this makes it all more compatible with the "edictor" type interface, which is basically a combination of very many different multi alignments)

**Comment by FrankNagel** [comment]
Fixed with commit 83ec3f4.
